name: Sync Pull Request to Azure Boards

on:
  pull_request_target:
    types: [opened, edited, closed]
    branches:
      - main

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
    - uses: danhellem/github-actions-pr-to-work-item@master
      env:
        ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'   
        github_token: '${{ secrets.GH_TOKEN }}'    
        ado_organization: 'gabrielgianotti0686'
        ado_project: 'teste'
        ado_wit: 'task' 
        ado_new_state: 'To Do'
        ado_active_state: 'Doing'
        ado_close_state: 'Done'
        ado_area_path: 'optional_area_path\\optional_area_path'
